CC = "arm64-apple-ios-simulator-clang"
CXX = "arm64-apple-ios-simulator-clang++"
CPP = "arm64-apple-ios-simulator-cpp"
AR = "arm64-apple-ios-simulator-ar"

CFLAGS = "-mios-version-min=13.0 --sysroot=\"{SDK_ROOT}\""
LDFLAGS = "-isysroot \"{SDK_ROOT}\""
